services:
  fastapi-sqlmodel-example:
    image: fastapi-sqlmodel-example:latest
    container_name: app
    ports:
      - 8000:8000
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASS: password
      DB_PORT: 3306
      DB_NAME: sqlmodel
      API_KEY: api-key 
    entrypoint: "uvicorn app.main:app --host 0.0.0.0 --port 8000"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network

  db:
    image: mariadb:latest
    container_name: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: password
    healthcheck:
      test: [ "CMD", "mariadb-admin", "ping", "-h", "localhost", "-u", "root", "--password=password" ]
      interval: 2s
      timeout: 20s
      retries: 20
      start_period: 3s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
